// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class User_SignUp
{
    public int User_Id { get; set; }

    public string User_Name { get; set; }

    public string User_Phonenumber { get; set; }

    public string User_Emailid { get; set; }

    public string Hash_Password { get; set; }

    public byte[] Salt_Password { get; set; }
}